### ISSUE TITLE
Need help to do vip daily reward

### ISSUE THREAD

**Issue by gorgioustheboss** [Wertzui123/Rewards#10]
hello, I would like to duplicate the plugin on my server to be able to make daily rewards only for vip and rewards for everyone and weekly rewards, I already try to edit to do it myself but having never touch php (especially plugins mcpe) I do not know how to do, I already try to duplicate put the perms in OP and with pure perm give them to VIPs I also change the name of the permissions but the players normal could still claim the rewards: / I did not find the discord to contact, we can contact us on discord Gorgious#5920

**Comment by Wertzui123** [comment]
My discord server can be found here: https://discord.gg/CDnERX

**Comment by Wertzui123** [comment]
I can send you a 2. version with other permissions via discord later, so you can use rewards 2 times
