### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by TetroYT** [Wertzui123/Rewards#11]
Better rewards for active players who claim the rewards everyday

so if someone claims the rewards everyday the rewards will progressively become better but if someone claims the rewards once a week or something they will keep getting the standard rewards

so lets say 
day 1: 10 diamond and $1000
day 2: 15 diamonds and $2000
day 3: a crate key $3000

and the rewards for each day can be setup in the config

maybe in the config it could be something like 

Progressive rewards: (using commands ofc)
 - day1: /give {player} diamonds 10
 - day2: /crate key (command changes depending on the plugin we are using
 - day3: 
    - /givemoney {player} 1000
    - /crate key (idk if this would work but it is for multiple rewards in 1)

etc

**Comment by SuperAdam47** [comment]
Same suggestion with #4

**Comment by Wertzui123** [comment]
Implemented in https://github.com/Wertzui123/Rewards/releases/tag/4.0.
