### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by MonoAdrian23** [Wertzui123/Rewards#13]
How can i add a Item with a namespace?

**Comment by Wertzui123** [comment]
What do you mean with "namespace"?

**Comment by MonoAdrian23** [comment]
diamond_ore
Zb.
Items with namespace cant be given.

**Comment by Wertzui123** [comment]
That's currently not possible, but I may add it.

**Comment by MassPepeng1701** [comment]
Ada Terjadi Bug Di Waktu Pengambilan Rewards...Saya Sudah Mengatur Waktu Untuk Mengambil Sehari Sekali...Pas Saya Coba Untuk Mengambil Rewards Berulang Kali Bisa Di Ambil Rewardsnya..Apakah Ada Saran Dari Anda Dan Kenapa Bisa Terjadi Begitu?

**Comment by Wertzui123** [comment]
Hello,

please use english or german to contact me. I don't speak this language.

**Comment by MassPepeng1701** [comment]
There Is A Bug When Taking A Prize ... I Have Set The Time To Take A Day Once ... When I Try To Take Prizes Repeatedly Can Take The Prizes ... Is There Any Advice From You And Why Can It Happen So?

**Comment by MassPepeng1701** [comment]
There Is A Bug When Taking A Prize ... I Have Set The Time To Take A Day Once ... When I Try To Take Prizes Repeatedly Can Take The Prizes ... Is There Any Advice From You And Why Can It Happen So?

**Comment by Wertzui123** [comment]
Hi, why did you close this issue?
