### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SuperAdam47** [Wertzui123/Rewards#4]
Add next days  different rewards example:

Day 1: 264:0:10
Day 2: 264:0:20
Day 3: 264:0:30, 291:0:1
Day 4: 5000$
Day 5: 264:0:10, 256:24
Day 6: 264:0:20, 321:0:5
Day 6: 264:0:60, 291:0:12
Day 7: 10000$

**Comment by Wertzui123** [comment]
Hm, but it reset after 1 week?

**Comment by SuperAdam47** [comment]
yes, same with pubg game daily reward system

**Comment by Wertzui123** [comment]
I don't know Pubg. But I'll try to implement it :wink:

**Comment by SuperAdam47** [comment]
now please?

**Comment by Wertzui123** [comment]
Maybe I'll add it soon, IDK.

**Comment by Wertzui123** [comment]
Implemented in https://github.com/Wertzui123/Rewards/releases/tag/4.0.
