### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by xDanub** [Wertzui123/Rewards#5]
Setup a way to give a permission node for different rewards. For example:
I want a way to reward players with ranks more than regular players. Make a way for players with ranks to get different items if they have say rewards.rank1

**Comment by Wertzui123** [comment]
Hm, I'll look about this Feature. It would be nice, but I'm working on other things at the moment so it could take a few weeks, up to months. But I hope I'll find time in the next weeks.

**Comment by Wertzui123** [comment]
This took me a year instead of a few weeks but it's now done. :wink:

**Comment by Wertzui123** [comment]
Implemented in https://github.com/Wertzui123/Rewards/releases/tag/4.0.
