### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SuperAdam47** [Wertzui123/Rewards#6]
[21:15:43] [Server thread/CRITICAL]: TypeError: "date() expects parameter 2 to be integer, boolean given" (EXCEPTION) in "plugins/Rewards_dev-52.phar/src/Wertzui123/Rewards/reward" at line 44

**Comment by Wertzui123** [comment]
Your config was generatet unsuccesfullly

**Comment by SuperAdam47** [comment]
I dont touched config file

**Comment by Wertzui123** [comment]
Hm, try a restart

**Comment by SuperAdam47** [comment]
same error

**Comment by Wertzui123** [comment]
Delete the config.yml, and restart the server 2 times

**Comment by SuperAdam47** [comment]
same error

**Comment by Wertzui123** [comment]
Show me your config

**Comment by SuperAdam47** [comment]
---
# This Plugin was written by Wertzui123 and you're not allowed to copy or clone it into you're plugin!
# You also musn't change the author or the license.
# © 2019 Wertzui123
#


#GENEREL DATA


#Don't edit the config version!
config_version: "2.0"

# The time format
# d = day
# m = month
# Y = Year
# H = Hour
# i = minute
time_format: "m.d.Y H:i"

# The time how long the players have to wait befor claiming their rewards again
# Please use minutes
# Example: "2222 minutes"
# 1440 minutes is one day
wait_time: "1440 minutes"

# These are the commands wich will be executed if the players get their rewards
# The commands will be executed trought the console
# {player} is the player who claimed his reward
# IMPORTANT: Use \" instead of normal quotess
commands:
 - msg {player} You got your reward!
 - "give {player} diamond 1  {display:{Name:\"§r§l§4Reward\"}}"


# COMMAND
# For help with the command configuration ask me on discord. xD
command: "reward"
description: "Claim your reward"
usage: "reward"
aliases: ["claimreward"]


#MESSAGES


# This is the message wich appears when you don't have the permission to use /reward
no_permission: "§cYou don't have the permission to use /reward"

# This is the message wich appears when you try to do "/reward" trough the console
run_ingame: "§cPlease run this command in-game"

# This is the message wich appears when you have to wait until you can claim you're reward again
already_got_reward: "§cYou already got you're reward today! You have to wait until §e{until}§c!"

# This is the message wich appears when you got you're reward
got_reward_succes: "§aYou succesfully got you're reward!"
...

**Comment by Wertzui123** [comment]
Hm, I'll look at it later

**Comment by Wertzui123** [comment]
Wich version do you use?

**Comment by SuperAdam47** [comment]
lastest

**Comment by setosakishima** [comment]
not yet solved?

**Comment by Wertzui123** [comment]
I don't know where the error is, because it works for me..

**Comment by Wertzui123** [comment]
Should be fixed, in the update later, please try.

**Comment by Wertzui123** [comment]
Technical problems, please wait

**Comment by Wertzui123** [comment]
Should be fixed, please test it out!

**Comment by SuperAdam47** [comment]
tested, no problems. thanks
