### ISSUE TITLE
Outdated for latest pocketmine

### ISSUE THREAD

**Issue by nebsonc** [Wertzui123/Rewards#7]
The console throws this error:
Error: "Call to undefined function Wertzui123\Rewards\int()" (EXCEPTION) in "plugins/Rewards_v2.0/src/Wertzui123/Rewards/reward" at line 44

**Comment by Wertzui123** [comment]
Thanks for reporting this bug. I'll try to fix it.

**Comment by Wertzui123** [comment]
Are you using "CB-Heads" too? If yes, does it throw the same error?

**Comment by Wertzui123** [comment]
Should be fixed, in the update later, please try.

**Comment by Wertzui123** [comment]
Technical problems, please wait for the update.

**Comment by Wertzui123** [comment]
Should be fixed, please test it out!

**Comment by Wertzui123** [comment]
@DeveloperNeb101 please test it out!

**Comment by Wertzui123** [comment]
I'll close this if you won't answer soon!
